language: cpp
compiler:
 - gcc
 - g++
before_install:
 - then echo "yes" |sudo apt-add-repository ppa:zoogie/sdl2-snapshots; fi
 - then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
 - then sudo apt-get update -qq; fi
 - then sudo apt-get install -y gcc-4.8 g++-4.8 libsdl-* libglm-dev libglew-dev libsdl2-dev python python-dev libboost-all-dev libboost-python-dev libboost-python1.48.0; fi
 - then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi
script:
 - autoreconf -i
 - ./configure
 - make
os:
 - linux
